Update requirements "h5py" missing in README
Executing "$ python output.py" returns the following error:

Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2017-11-13 13:11:08.607633: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "output.py", line 38, in <module>
    model.load_weights(weight_path)
  File "/usr/lib/python3.6/site-packages/keras/engine/topology.py", line 2615, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.

Adding h5py (2.7.1) to requirements list.